### ISSUE TITLE
Bot fails to respond on /addcan while it's on cooldown

### ISSUE THREAD

**Issue by luminantAegis** [LumiRadio/lumiRadio#32]
As title. 

Expected: /addcan returning a message visible only to the user mentioning the command is on cooldown

Actual:
![image](https://github.com/LumiRadio/lumiRadio/assets/22201350/c4e17508-d832-41b5-86c8-72c1e3439d57)

`!addcan` is emulating old byers when it doesn't respond under cooldown and is not part of this issue (and imo shouldn't be to reduce bot's message density)

**Comment by cozyGalvinism** [comment]
Yup, found the issue. Will be fixed in 1.2.0.
